### ISSUE TITLE
related reference display name heuristic

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#215] opened 2016-09-27 22:54 UTC
When the reference api determines the display name for a related reference, if the related reference is related via an association table, then the (default) for the display name should be the display name of the association table _not_ the display name of the related table itself. The explain why, see the attached screenshot of the record(2) app. We have a table `dataset` that has three associations with the `file` table, for images, previews, and downloads. Because of the heuristic in ermrestjs not following the rules above, those three tables are all called "FILE" in the display, when they should have been named "DATASET PREVIEW", "DATASET IMAGE", and "DATASET DOWNLOAD".
![files](https://cloud.githubusercontent.com/assets/4202842/18894899/9ae6524a-84ca-11e6-898a-024a3391ad9c.jpg)

**Comment by hongsudt** [comment] 2016-09-27 23:17
This is a duplicate of #210. Will close this issue.

**Closed by hongsudt** 2016-09-27 23:17 UTC
Labels: bug
