### ISSUE TITLE
Need more precision in floating point number display

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/ermrestjs#295] opened 2016-11-30 18:34 UTC
I need more than two digits of fraction in the floating point display. My project has small values which are being rounded and truncated too much and giving poor UX.

In the long run, the pre_format display option is meant to allow this to be customized. I know there are some concerns about which formatting language and library to use here.

In the short term, I need either a simpler deployment config option to adjust precision of the current rounding, or a hard-coded change to increase the rounding width to 4 fractional decimal digits (which would be good enough to address my current UX problem).

Right now, we have values like 0.001 and 0.007 being visible in recordedit app but being rounded to 0.00 and 0.01 in the record app.

@hongsudt  @robes

**Comment by hongsudt** [comment] 2016-12-07 02:58
duplicate of #299.

**Closed by hongsudt** 2016-12-07 02:58 UTC
