### ISSUE TITLE
Create with not null column not in visible columns list with default value

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#688] opened 2018-08-15 23:35 UTC
If you have a column that is marked as "not null" (required) and is not part of the visible columns list and there is a default value defined for that column, an error is thrown (`<column name> is missing error`).

This looks like a flaw in the logic for ermrestJS.

**Comment by RFSH** [comment] 2018-08-27 17:27
I [recreated](https://dev.isrd.isi.edu/~ashafaei/chaise/recordedit/#49438/product:t_test) the exact describe situation, but I didn't get any errors. The `col_invisible` is not part of the visible columns, has `nullok: false` and `default: "value"`. You can see that after creating the entity, `value` is inserted for that column (because we're adding any invisible columns to the list of default values).

There might be some other factors involved here. Is this currently happening in any of the deployments?

**Comment by RFSH** [comment] 2018-08-28 00:47
Since we're not able to reproduce this behavior anymore, I am going to close this issue. While taking a look at this one, we found that we could make some improvement to the logic that we have in `create` function for creating the list of defaults. I created [another issue](https://github.com/informatics-isi-edu/ermrestjs/issues/696) for this.

**Closed by RFSH** 2018-08-28 00:47 UTC
