### ISSUE TITLE
Histogram API returns inconsistent buckets

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/ermrestjs#600] opened 2018-02-15 00:06 UTC
The histogram API returns a different set of buckets when the server is run locally (on dev.isrd with `US/Pacific` timezone) and when it runs on travis (with server set as `UTC`).

It seems that there is a difference in how postgres does calculations for values based on UTC and values based elsewhere with daylights savings calculated in.

**Comment by hongsudt** [comment] 2018-03-01 20:23
@jrchudy I thought we have solved this problem.. If so, can you update the issue and close it?

**Comment by jrchudy** [comment] 2018-03-01 23:17
No we didn't. The issue is no longer present in our test cases because I change the scope of the data so that all of the timestamp data falls within one 8 month period that doesn't change from PST to PDT (daylights savings).

**Comment by hongsudt** [comment] 2018-03-01 23:29
So this is the issue with day-light saving?

**Comment by RFSH** [comment] 2018-03-01 23:31
We found out that it's not that the server (postgres) or client (moment) are misbehaving, just that postgres will store the data the same way that is given (if the timezone offset is set to -7:00 it will store it with that offset regardless of client timezone). And its client's responsibility to attach the correct timezone to the data that is submitting to the server.

And we were seeing these inconsistencies in our test cases because the data that we were feeding was in the daylight saving time-period, but we were passing the PST offset. So the server would store them with -8:00 offset, but the client (because of daylight saving) would change them to -7:00 offset.

**Comment by RFSH** [comment] 2019-05-03 22:00
@jrchudy I think we can close this issue. This was just an issue in seeding the test data, not a bug in our platform.

**Closed** 2019-05-06 19:21 UTC
