### ISSUE TITLE
General search feature improvement

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ermrestjs#744] opened 2018-12-05 19:05 UTC
People sometimes get confused on the expectation of the general search feature (e.g. the search box on top of the result set). For example, on the gene page, they assume that the search should only search on the gene Name and Synonyms. People get confused when there are many false positives. Here are a few things that I think can help alleviate some of these confusion: 
- [ ] Provide advanced search feature that first allow dba to configure the scope of the search within a table. As a starting point, we can focus on columns within the same table. 
- [ ] Change the hint text to be more specific whether it is a column search of table search
  - column search: search <column1>, <column2>
  - table search: search all columns in a table
- [ ] Provide GUI for users to set the scope themselves 
- [ ] Extend the search to go beyond one table (See #353).

**Comment by hongsudt** [comment] 2019-09-04 19:11
The first 2 bullets should be part of the UX mitigation plan to address the custom filter for GUDMAP gene sesarch.

**Comment by RFSH** [comment] 2019-09-24 16:48
### How should we define the list of search columns?
 For defining search columns, we can add define a new context called "search" under `visible-columns`.  DBAs should be able to define pseudo-columns here as well. We might want to define which types of pseudo-columns are allowed here. Does it have to be all-outbound paths?

### What should be the displayed as placeholder in search box?
We are going to show displayname of column names in the search input placeholder in the format of "Search col1, col2, and col3". We should show the parsed HTML values of displaynames in the placeholder (i.e. If you have bold text, the displayed placeholder will be bold). It will be the DBAs responsibility to ensure that the displayname value and representation makes sense as a placeholder.

What should we use as placeholder when the `search` context is missing? Should we use the table displayname ("Search within tablename")? If so, the table name can be markdown and DBAs cannot customize it in this case. Or should we use the general static "search all columns" placeholder instead?

**Comment by RFSH** [comment] 2019-10-08 16:49
We had a discussion about this feature, the following are important point of it:


### Current main search syntax in facets

Currently the main search is stored as part of facets. If you go to a recordset page with `test` in the main search, the following is what ermrestjs will store in the url as a facet:

```json
{
  "and": [
    {"source": "*", "search": ["test"]}
  ]
}
```

This has been done to make it easer for ermrestjs to parse the url. We're treating `*` as special case and we're only looking for the `search` filter in this syntax. It is also consistent with other types of facet sources. They all support having `search` filter in ermrestjs, so we didn't need to add any extra logic of parsing the `search` filter in here.

We might want to change this to be more robust. It is a hacky implementation and It might not be very clear what the `"source": "*"` means and also there might be a column called `*` in the table.

#### What should be stored in url

The first option is only storing the search term in the url. By doing so we rely on the annotation and internal ermrestjs logic to determine the search columns. This will allow us to decouple the urls that users might have stored in their permalink from the annotation. But it might be confusing since with the same search text chaise might return different results (if the annotation changes), and users cannot capture the current state of the page using the permalink. Which this brings up another question of what is the expected behavior of permalink? 

At the minimum I think we should be able to just store the search term in the url and let ermrestjs/chaise handle it. We might want to add an extra attribute that can be specified in the url. In that case ermrestjs/chaise should ignore the annotations and use the columns defined in the url.

**Comment by RFSH** [comment] 2019-10-10 01:54
We have another discussion about this feature, the following are its results:

- We should not encode anything apart from the search term in the url. The search columns should only come from the annotation.
- We should revisit the syntax for encoding search and remove it from the facets. It should be its own pseudo-operator. We can use the `*::search::<search term>` syntax for it.
- The list of search columns should be defined in a proper filter syntax and we are only going to support disjunction for now. So

```javascript
"tag:isrd.isi.edu,2016:visible-columns": {
  "search-box": {
    "or": [
         // list of column definitions
    ]
  }
}
```

- We should be able to refer to the whole table in the list of columns. This is to allow mixing search on a table with another without specifying the search columns. The following are the suggested syntaxes:

```javascript

//version1
{
  "or": [
    {"source": true}, // all the columns in the main table
    {"source": [{"outbound": ["s", "c"]}, true] // all the columns in a path
  ]
}


//version2
{
  "or": [
    {"source": {"unquoted": "*"}}, // all the columns in the main table
    {"source": [{"outbound": ["s", "c"]}, {"unquoted": "*"}] // all the columns in a path
  ]
}
```
The first version is easier to read, but might not be very extensible. Also the second version is closer to actual implementation of this feature and might be easier to understand and follow.

**Comment by karlcz** [comment] 2019-10-10 02:38
Actually, this isn't quite right.  I think the URL parameter should
just be something like:

  searchbox=encoded-user-text

there is no sense in having the "*" appear anywhere in there. That is
strictly related to the configuration of the searchbox function
which will appear in the annotations.

**Comment by RFSH** [comment] 2019-10-14 18:01
@karlcz 
ermrsetjs will interpret `searchbox=encoded-user-text` as a filter and I didn't want to add a rule to treat `searchbox` name as the main search box.

That's why I tried to use a different syntax and I thought I should follow the same pattern that ermrest has for binary predicates. I did the same with facets as they are represented in `*::facets::<facet-hash>` format in the url.

So should I assume that there's no `searchbox` column in the table and treat `searchbox=value` differently? Or should I use another more meaningful syntax? (`::search::<term>` ? )

**Comment by RFSH** [comment] 2019-10-22 17:14
We had another discussion about this. The following is the final draft of what needs to be implemented:

- We should support `sourcekey` in the facet blob.  So the following should be supported:
  ```json
  {
    "and": [
      {"sourcekey": "some-defined-source-key", "choices": ["test"]},
    ]
  }
  ```
  where `some-defined-source-key` is a valid source-definition.

- sourcekey `search-box` is reserved for defining the search columns. The following is how it should be defined:

  ```javascript
  "tag:isrd.isi.edu,2019:source-defnitions": {
    "sources": {
      "search-box": {
        "or": [
          {"source": "col", "markdown_name": "column"},
          {"source": "col2", "markdown_name": "column 2"},
        ]
      }
    }
  }
  ```


- Main search term will be encoded like the rest of facets in the facet blob using the `sourcekey` syntax. So assuming that you have `term` in the search box, the following will be the facet blob:

  ```javascript
  {
    "and": [
      {"sourcekey": "search-box", "search": ["term"]},
      {"source": "column", "choices": ["value"]}
    ]
  }
  ```

**Comment by RFSH** [comment] 2019-11-25 19:21
We've merged the first iteration of these changes which include:

- Support `sourcekey` in the facet part of URLs.
- Add basic support of normal columns for the special `search-box` sourcekey.


While implementing this, I spend some time to figure out the ways that we can implement the foreign key paths in the search columns. These are the key points that came to my mind:

- If only one search column defined, if it has a foreign key path, we should use inner join.
- If more than one search column is defined, the main result is the disjunction of each search term. So we should use outer join for foreign key paths.
- Because of the same issues that we faced while parsing facets for the `null` check, we should not use left outer join. 
- We cannot have multiple right outer joins in the URL.

I'll explain this using some examples. Assume that the following is the ERD of our schema and we're defining the search columns for table `M`:

![](https://raw.githubusercontent.com/informatics-isi-edu/ermrestjs/master/docs/resources/pseudo_columns_erd_01.png)

The following is how I think we should translate a given `search-box` to ermrest query assuming that the search term is `term`. To preserve some space in the table I presented the list of search columns as a flat list of their `source` definitions. So for example `"text_col"`, `"int_col"` is in fact:

```json
"or": [
  {"source": "text_col"},
  {"source": "int_col"}
]
```

| search columns                                                                                | ermrest query                                                                                                     |
|-----------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|
| not defined                                                                                   | `M:=s:main/*::ciregexp::term/$M`                                                                                  |
| `"text_col"`, `"int_col"`                                                                     | `M:=s:main/text_col::ciregexp::term;int_col::ciregexp::term/$M`                                                   |
| `[{"outbound": ["s", "fk1_cons"]}, "f1_text"]`                                                | `M:=s:main/(fk_col)=(F1:f1_id)/f1_text::ciregexp::term/$M`                                                        |
| `"text_col"`, `[{"outbound": ["s", "fk1_cons"]}, "f1_text"]`                                  | `M:=s:main/left(fk_col)=(F1:f1_id)/M:text_col::ciregexp::term;f1_text::ciregexp::term/$M`                         |
|                                                                                               | `s:F1/f1_text::ciregep::term/M:=right(f1_id)=(Main:fk_col)/text_col::ciregexp::term/$M`                           |
| `[{"outbound": ["s", "fk1_cons"]}, {"outbound": ["s", "fk5_cons"]}, "f5_text"]`               | `M:=s:main/(fk_col)=(F1:f1_id)/(fk_to_f5)=(F5:f5_id)/f5_text::ciregexp::term/$M`                                  |
| `"text_col"`, `[{"outbound": ["s", "fk1_cons"]}, {"outbound": ["s", "fk5_cons"]}, "f5_text"]` | `S:F5/f5_text::ciregexp::term/(f5_id)=(F1:fk_to_f5)/M:=right(F1:f1_id)=(Main:fk_col)/text_col::ciregexp::term/$M` |

Based on this, these are the restrictions that we have:

- We cannot support more than one foreign key path in the search columns.
- Searching based on a column with a foreign key path cannot co-exist with the existing facet `null` checks that use right outer join.

I wrote this based on my understanding of ermerst which might be wrong. @karlcz Can you please take a look at this and review it?

**Comment by RFSH** [comment] 2021-02-26 23:27
Based on the limitations listed, one suggestion was allowing the addition of a single outbound foreign key path for now, instead of trying to find a general solution. 

This feature would be useful in Facebase deployment.

**Comment by karlcz** [comment] 2021-03-02 18:27
Just to make sure we're on the same page, the limitation is about the `"or"` disjunctive list of sources for the search-box.  You need to do an outer join if the search-box has to match on more than one source and any of the sources requires a join. You can skip this if there is only a single source.

That means you cannot even mix a single join with local columns of the table. A deployment using joins would have to build a term/indexing table for all entity content to be matched by the searchbox, including base row content. They cannot just build a table to link in auxilliary terms.

**Comment by karlcz** [comment] 2021-03-08 20:21
I don't think I need this for my project right now, but I think we should consider something like an "inner_join_safe: true" setting that a DBA can make on a source definition to allow Chaise to blindly do inner joins for the search-box disjunctive list of sources.  It would be the DBA's job to ensure that the inner join will not in itself exclude rows relevant to the search, e.g. because they know that the path represents a 1-or-more relationship in practice _for every row that the client is allowed to select_.  I.e. they need to think about their relational data and their policy environment when declaring this safety property.

**Comment by RFSH** [comment] 2021-10-04 19:26
I'm going to close this issue in favor of #906

**Closed by RFSH** 2021-10-04 19:26 UTC
Labels: info needed
