### ISSUE TITLE
API to get all tables with a FKR to this table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/ermrestjs#58] opened 2016-06-22 00:19 UTC
Tables that they have a foreign key to this table (for now, I loop over all the tables and find out if they have foreign key to the specified table).

**Comment by robes** [comment] 2016-06-23 18:26
@RFSH what I would suggest considering here is whether it would be preferable to "get all FKRs that refer to this table" instead of getting "all tables with a FKR to this table". I question whether you really only need to know about the _tables_ that refer to this table rather than the _FKRs_ of a table that refer to this table.

**Comment by RFSH** [comment] 2016-06-23 18:36
Eventually what I need is both of them. To show the table and know why that table is related (know the columns that are involved in the FKR). Although I can find the tables from FKRs themselves.

**Comment by RFSH** [comment] 2016-06-24 18:47
@robes 
In #64 you mentioned that we may not need to display associative tables. This can affect what is needed in here too. Because if we want to ignore the associative table, we need to find the other tables that are part of this association and list them as tables that are related to the selected table. For instance, instead of `dataset_human_gender` the API should return `human_gender`.

Then the requested API is not just finding the tables with FKR to this table.

Also, what if the associative table has extra columns. Shouldn't that columns be part of selectable attributes for matrix? or We should ignore that table altogether?

**Comment by robes** [comment] 2016-06-24 21:26
@RFSH Yes, one thought has been to have a property of a table to find the associations that make reference to it. In a way these types of features are similar to the Column level memberOfForeignKeys

https://github.com/informatics-isi-edu/ermrestjs/blob/master/doc/api.md#ERMrest.Column+memberOfForeignKeys

We may want to have an api at the Table level like:

```
Table
  .referencedBy() => [ ForeignKeyRef... ]
  .associatedBy() => [ ForeignKeyRef... ] /* this would be redundant with referenceBy */
```

Needs to be given more thought.

**Comment by RFSH** [comment] 2016-07-29 23:07
Duplicate of #105.

**Closed** 2016-08-01 22:42 UTC
